// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMogqcde2SaoIMGeFG2yUSFPZh-4all7Q',
    appId: '1:661400754508:web:6368f7ce3f7e81897e17e9',
    messagingSenderId: '661400754508',
    projectId: 'finaltest-ed074',
    authDomain: 'finaltest-ed074.firebaseapp.com',
    storageBucket: 'finaltest-ed074.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD-sUvyXQdZqdGsRpj9je0pz2FOnBnXUI',
    appId: '1:661400754508:android:ee09beeabacc59857e17e9',
    messagingSenderId: '661400754508',
    projectId: 'finaltest-ed074',
    storageBucket: 'finaltest-ed074.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsCMWYu9qSJIBHt5HsTJLwEtLfvS98YNA',
    appId: '1:661400754508:ios:050b78b81023c37c7e17e9',
    messagingSenderId: '661400754508',
    projectId: 'finaltest-ed074',
    storageBucket: 'finaltest-ed074.appspot.com',
    iosBundleId: 'com.example.finalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMogqcde2SaoIMGeFG2yUSFPZh-4all7Q',
    appId: '1:661400754508:web:d05c07a1972ed7217e17e9',
    messagingSenderId: '661400754508',
    projectId: 'finaltest-ed074',
    authDomain: 'finaltest-ed074.firebaseapp.com',
    storageBucket: 'finaltest-ed074.appspot.com',
  );
}
